#!/usr/bin/env node
// Writes docs/MD_DATA_STATUS.md from the county files in data/real/.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCSV } from '../lib.mjs';
import { totals, scoreTown } from '../../js/engine/scoring.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'data', 'real');
const lgf = JSON.parse(readFileSync(join(ROOT, 'data', 'raw', 'md', 'lgf.json'), 'utf8'));
const places = parseCSV(readFileSync(join(ROOT, 'data', 'raw', 'md', 'popest.csv'), 'latin1')).filter((r) => r.sumlev === '162');
const rows = [];
const admin = [];
const scores = [];
const older = [];
let covered = 0;
let latest = 0;
const files = readdirSync(OUT).filter((f) => /^md-.*\.json$/.test(f)).sort();
for (const f of files) {
  const { towns } = JSON.parse(readFileSync(join(OUT, f), 'utf8'));
  for (const t of towns) {
    latest = Math.max(latest, t.fiscalYear);
    admin.push(totals(t).adminShare);
    scores.push(scoreTown(t).score);
  }
  covered += towns.length;
  const kinds = ['City', 'Town', 'Village'].map((k) => [k, towns.filter((t) => t.type === k).length]).filter(([, n]) => n)
    .map(([k, n]) => `${n} ${k === 'City' ? (n === 1 ? 'city' : 'cities') : `${k.toLowerCase()}${n === 1 ? '' : 's'}`}`).join(', ');
  const fy = [...new Set(towns.map((t) => t.fiscalYear))].sort();
  rows.push(`| ${towns[0].county} | ${towns.length} (${kinds}) | ${fy.join(', ')} | ${towns.filter((t) => typeof t.debt === 'number').length} |`);
  older.push(...towns.map((t) => [t.name, t.fiscalYear]));
}
const median = (a) => a.sort((x, y) => x - y)[a.length >> 1];
const behind = older.filter(([, y]) => y < latest).map(([n, y]) => `${n} (FY ${y})`).sort();
const loaded = new Set(older.map(([n]) => n.replace(/^(City|Town|Village) of /, '')));
const missing = places.map((p) => p.name.replace(/ (city|town|village)$/, '')).filter((n) => n !== 'Baltimore' && !loaded.has(n) && !loaded.has(n.replace(/ Village$/, '')))
  .map((n) => n.replace(/ Section (Three|Five)$/, (m, x) => ` Section ${x === 'Three' ? 3 : 5}`));
const years = Object.keys(lgf).sort();
writeFileSync(join(ROOT, 'docs', 'MD_DATA_STATUS.md'), `# Maryland data status

Generated by \`node scripts/md/status.mjs\`. ${covered} governments loaded: ${covered - 1} of Maryland's ${places.length - 1} other incorporated municipalities and Baltimore City, grouped by county. Counties themselves (which run schools, most police and most other services) and State-created special taxing districts are not included.

| County | Loaded | Fiscal year(s) | Debt |
|---|---|---|---|
${rows.join('\n')}

## Sources
- **Revenue, spending and debt:** MD Department of Legislative Services, [Local Government Finances in Maryland](https://dls.maryland.gov/budget/local-finances/), FY ${years[0]}-${years.at(-1)}. Each government's uniform financial report, adjusted and reconciled by DLS to its audited financial statements: revenue by source and spending by function for governmental operating, governmental capital and enterprise funds, and public debt outstanding. Published as PDF; \`lgf-to-json.py\` reads the tables by position with pdfplumber.
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer.

## How Maryland differs
- **Counties do most of the work.** Schools, most policing, and many roads and utilities are county services, so municipal budgets are small and general government is a large share: the median town spends ${Math.round(median(admin) * 100)}% of its budget on general government, economic and community development (NJ, NY and PA are 15-17%). Baltimore City is an independent city that runs its own schools; its transfers to the school system are shown as schools and left out of the services and overhead shares.
- **All funds are counted.** Governmental operating, capital and enterprise columns are all included, so water, sewer and electric utilities run by a town count, and capital spending counts in the year it happens. Debt proceeds are left out. Miscellaneous spending (pensions, health insurance, Social Security, judgments) is spread across departments by size, except debt service.

## Known gaps
- **No financial information submitted** for any year loaded: ${missing.length ? missing.join(', ') : 'none'}. They are not listed.
- **Older year used** because the town did not report for FY ${latest}: ${behind.length ? behind.join(', ') : 'none'}.
- **Political money is not scored.** Candidates for municipal office file campaign reports with their municipality. Baltimore City candidates file with the State Board of Elections, whose data has not been loaded yet.
- **Transparency practices** have not been checked yet, so they are not scored.
- The median score is ${Math.round(median(scores))}, on services, overhead and fiscal health only.
`);
console.log(`docs/MD_DATA_STATUS.md: ${covered} governments`);
