#!/usr/bin/env node
// Writes docs/VT_DATA_STATUS.md from the county files in data/real/ and the last
// `build-county.mjs --all` report.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { totals, scoreTown } from '../../js/engine/scoring.js';
import { YEARS } from '../common/census-units.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'data', 'real');
const report = JSON.parse(readFileSync(join(ROOT, 'data', 'raw', 'vt', 'build-report.json'), 'utf8'));
const towns = readdirSync(OUT).filter((f) => /^vt-.*\.json$/.test(f)).flatMap((f) => JSON.parse(readFileSync(join(OUT, f), 'utf8')).towns);
const median = (a) => a.sort((x, y) => x - y)[a.length >> 1];

const rows = ['County', 'City', 'Town', 'Village'].map((kind) => {
  const g = towns.filter((t) => t.type === kind);
  const fy = YEARS.map((y) => `${y}: ${g.filter((t) => t.fiscalYear === y).length}`).join(', ');
  return { kind, n: g.length, fy, score: g.length && Math.round(median(g.map((t) => scoreTown(t).score))), admin: g.length && Math.round(median(g.map((t) => totals(t).adminShare)) * 100) };
});
const label = { County: 'Counties', City: 'Cities', Town: 'Towns', Village: 'Villages' };
const list = (a) => { const s = [...new Set(a)].sort(); return s.length ? s.join(', ') : 'none'; };
const imputed = [...new Set(report.imputed)];
const incomplete = [...new Set(report.incomplete)];
const billing = towns.filter((t) => t.type === 'Town' || t.type === 'City').length;

writeFileSync(join(ROOT, 'docs', 'VT_DATA_STATUS.md'), `# Vermont data status

Generated by \`node scripts/vt/status.mjs\`. ${towns.length} governments loaded. Vermont's 237 towns and 10 cities are its main local governments. About 30 incorporated villages are a second layer inside their towns, and the 14 counties run little more than the courthouse and the sheriff. Public schools are run by school districts funded through the statewide Education Fund. Each county's file holds the county and its cities, towns and villages.

| Type | Loaded | Fiscal year used (count) | Median score | Median overhead |
|---|---|---|---|---|
${rows.filter((r) => r.n).map((r) => `| ${label[r.kind]} | ${r.n} | ${r.fy} | ${r.score} | ${r.admin}% |`).join('\n')}

## Sources
- **Revenue, spending and debt:** what each government reported to the U.S. Census Bureau's [Annual Survey of State and Local Government Finances](https://www.census.gov/programs-surveys/gov-finances.html) (individual unit files), FY ${YEARS[0]}-${YEARS.at(-1)}, with the same mapping as the Carolinas, Delaware and New Hampshire. The Census counts Vermont's towns as township governments. ${YEARS[0]} is a Census of Governments year covering every government; later years cover a sample, so each government's latest reported year is used. Vermont has no central collection of town financial reports: each town publishes its own annual town report.
- **Education and municipal property tax by town:** Vermont Department of Taxes, [Property Valuation and Review annual report data](https://tax.vermont.gov/pvr-annual-report) (taxes and tax rates by town, tax years 2021-2024).
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer (county subdivisions and places).

## How Vermont differs
- **Education tax on the town bill.** Each town and city bills the statewide education property tax along with its own municipal tax and pays it over to the school district. ${report.passThrough.length} of the ${billing} towns and cities loaded reported the whole levy to the Census as their own property tax. For those, the education tax the Department of Taxes lists for the town is taken out, so only the municipal share is counted. Each affected town's report says so and gives the amounts. Unlike New Hampshire, where the town's share has to be estimated, Vermont publishes both figures for every town.
- **Villages inside towns.** Incorporated villages run their own services (often water, sewer, electric, police or streets) and residents pay both the village and the town. Villages do not bill education tax.
- **Payments to other governments are left out**, as in the Carolinas, Delaware and New Hampshire.

## Known gaps
- **Political money is not scored.** The Secretary of State's campaign finance system refused connections from the build environment, both its own site and the Secretary of State's website. Most town candidates do not file there anyway.
- **Estimated by the Census, not reported (left out, ${imputed.length}):** ${list(imputed)}.
- **Incomplete in the Census files (only debt or a few figures, or spending under a quarter of revenue; left out, ${incomplete.length}):** ${list(incomplete)}.
- **Revenue and spending more than four times apart (left out, ${report.inconsistent.length}):** ${list(report.inconsistent)}.
- **Older year used** because the latest sampled year was estimated, incomplete or inconsistent: ${report.older.length ? report.older.join(', ') : 'none'}.
- **No longer a government:** ${report.skipped.length ? report.skipped.map((s) => s.replace(/^LYNDONVILLE VILLAGE: no Census match$/, 'the Village of Lyndonville, which the Census 2025 estimates list only as a Census-designated place in the Town of Lyndon').replace(/: no Census match$/, ' (no Census geography)')).join(', ') : 'none'}.
- **Not in the Census files:** unorganized towns and gores (in Essex and Bennington counties) have no government of their own.
- **Transparency practices** have not been checked yet, so they are not scored.
`);
console.log(`docs/VT_DATA_STATUS.md: ${towns.length} governments`);
