#!/usr/bin/env node
// Writes docs/GA_DATA_STATUS.md from the county files in data/real/ and the last
// `build-county.mjs --all` report.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { totals, scoreTown } from '../../js/engine/scoring.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'data', 'real');
const RAW = join(ROOT, 'data', 'raw', 'ga');
const report = JSON.parse(readFileSync(join(RAW, 'build-report.json'), 'utf8'));
const index = JSON.parse(readFileSync(join(RAW, 'rlgf-index.json'), 'utf8'));
const towns = readdirSync(OUT).filter((f) => /^ga-.*\.json$/.test(f)).flatMap((f) => JSON.parse(readFileSync(join(OUT, f), 'utf8')).towns);
const median = (a) => a.sort((x, y) => x - y)[a.length >> 1];
const years = [...new Set(towns.map((t) => t.fiscalYear))].sort();

const kinds = ['County', 'Consolidated government', 'City', 'Town'];
const label = { County: 'Counties', 'Consolidated government': 'Consolidated governments', City: 'Cities', Town: 'Towns' };
const rows = kinds.map((kind) => {
  const g = towns.filter((t) => t.type === kind);
  return { kind, n: g.length, fy: years.map((y) => `${y}: ${g.filter((t) => t.fiscalYear === y).length}`).join(', '),
    score: g.length ? Math.round(median(g.map((t) => scoreTown(t).score))) : '-', admin: g.length ? `${Math.round(median(g.map((t) => totals(t).adminShare)) * 100)}%` : '-' };
});

writeFileSync(join(ROOT, 'docs', 'GA_DATA_STATUS.md'), `# Georgia data status

Generated by \`node scripts/ga/status.mjs\`. ${towns.length} of the ${index.length} governments DCA lists are loaded. Georgia has no townships: counties (or consolidated city-county governments) serve everyone, and cities and towns are a second layer inside them. Public schools are run by separate school districts. Each county's file holds the county and the cities whose people mostly live in it.

| Type | Loaded | Fiscal year used (count) | Median score | Median overhead |
|---|---|---|---|---|
${rows.map((r) => `| ${label[r.kind]} | ${r.n} | ${r.fy} | ${r.score} | ${r.admin} |`).join('\n')}

## Sources
- **Revenue, spending and debt:** GA Department of Community Affairs, [Report of Local Government Finance](${'https://dca.georgia.gov/community-assistance/government-authority-reporting/report-local-government-finance-rlgf'}) (RLGF), which every county, city and consolidated government must file each year, from audited figures where available. Each report's machine-readable sheet gives taxes and other revenue by UCOA account, intergovernmental revenue by source, utility and enterprise revenue, spending by UCOA function (current operations and capital outlay), enterprise fund expenses, payments to other governments, and debt issued, retired, outstanding and interest paid. Reports are downloaded from the [DCA viewer](https://apps.dca.ga.gov/RLGF/Default.aspx). Every loaded government's revenue and spending reconcile to the totals on its own report${report.mismatch.length ? `, except the ${report.mismatch.length} listed below` : ''}.
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer.

## How Georgia differs
- **Schools are separate.** School districts are their own governments, so county and city reports do not include schools.
- **Consolidated governments** (Athens-Clarke, Augusta-Richmond, Columbus, Macon-Bibb and smaller ones) provide county and city services across their county, so they are listed with the county's population.
- **Payments to other governments are left out**, as in North and South Carolina: the receiving government reports that spending. That includes SPLOST sales tax proceeds that counties pass to cities, which the cities report as revenue.
- **Political money is not scored.** County and city candidates file campaign reports with their county election superintendent or city clerk, not with a statewide agency, so there is no statewide source.

## Known gaps
- **No report filed with DCA since FY ${2022} (left out, ${report.notFiled.length}):** ${report.notFiled.length ? report.notFiled.join(', ') : 'none'}.
- **Not matched to Census geography:** ${report.skipped.length ? report.skipped.join(', ') : 'none'}.
- **Older year used** because the latest report is empty: ${report.older.length ? report.older.join(', ') : 'none'}.
- **Reports whose own totals do not match their lines:** ${report.mismatch.length ? report.mismatch.join('; ') : 'none'}.
- **Transparency practices** have not been checked yet, so they are not scored.
`);
console.log(`docs/GA_DATA_STATUS.md: ${towns.length} governments`);
