#!/usr/bin/env node
// Writes docs/NY_DATA_STATUS.md from the county files in data/real/.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { slugify } from '../lib.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
// Without the raw Comptroller file (data/raw is not committed), counties come from
// the loaded files and the governments-on-file total is the last published one.
const oscPath = join(ROOT, 'data', 'raw', 'ny', 'osc.json');
const osc = existsSync(oscPath) ? JSON.parse(readFileSync(oscPath, 'utf8')) : null;
const LAST_OSC_TOTAL = 1536;
const counties = osc
  ? [...new Set(Object.values(osc).map((g) => g.county))].sort()
  : [...new Set(JSON.parse(readFileSync(join(ROOT, 'data', 'real', 'index.json'), 'utf8')).files.filter((f) => f.startsWith('ny-'))
    .map((f) => JSON.parse(readFileSync(join(ROOT, 'data', 'real', f), 'utf8')).towns[0]?.county.replace(/ County$/, '')).filter(Boolean))].sort();
const has = (o) => o && typeof o === 'object' && Object.keys(o).length > 0;

const rows = [];
let total = 0;
let covered = 0;
const old = [];
for (const county of counties) {
  const file = join(ROOT, 'data', 'real', `ny-${slugify(county)}.json`);
  const inOsc = osc ? Object.values(osc).filter((g) => g.county === county).length : 0;
  if (!existsSync(file)) { rows.push(`| ${county} | not started | | | | | | |`); continue; }
  const { towns } = JSON.parse(readFileSync(file, 'utf8'));
  const n = (f) => towns.filter(f).length;
  const types = ['Town', 'Village', 'City'].map((k) => `${n((t) => t.type === k)} ${k.toLowerCase()}${n((t) => t.type === k) === 1 ? '' : 's'}`).filter((s) => !s.startsWith('0 ')).join(', ');
  const years = [...new Set(towns.map((t) => t.fiscalYear))].sort();
  old.push(...towns.filter((t) => t.fiscalYear < 2023).map((t) => `${t.name} (${t.fiscalYear})`));
  total += inOsc;
  covered += towns.length;
  rows.push(`| ${county} | ${towns.length} (${types}) | ${years.length > 2 ? `${years[0]}-${years.at(-1)}` : years.join(', ')} | ${n((t) => typeof t.debt === 'number')} | ${n((t) => Object.values(t.influence || {}).some((v) => v > 0))} of ${n((t) => has(t.influence))} | ${n((t) => has(t.transparency))} | ${n((t) => t.redFlags?.length)} of ${n((t) => Array.isArray(t.redFlags))} |`);
}

writeFileSync(join(ROOT, 'docs', 'NY_DATA_STATUS.md'), `# New York data status

Generated by \`node scripts/ny/status.mjs\`. ${covered} towns, villages and cities loaded (the State Comptroller's files list ${osc ? total : LAST_OSC_TOTAL} governments since 2016, including villages that have since dissolved).

| County | Loaded | Report year(s) | Debt | Political money (with any / loaded) | Transparency | Red flags (flagged of checked) |
|---|---|---|---|---|---|---|
${rows.join('\n')}

## Sources
- **Revenue and spending:** NY Office of the State Comptroller, [Financial Data for Local Governments](https://wwe1.osc.state.ny.us/localgov/findata/financial-data-for-local-governments.cfm): each government's latest Annual Financial Report (actual results, not budgets). Custodial and trust funds, the internal self-insurance fund, transfers between a government's own funds, and bond refinancing are left out because they are not the government's own new money; every build checks that counted plus left-out amounts equal the reported totals.
- **Debt:** the Comptroller's debt data, outstanding at the end of the report year (revenue and tax anticipation notes left out as short-term cash-flow borrowing).
- **Population:** U.S. Census Bureau 2025 population estimates for cities, towns and villages. **Map location:** Census 2024 Gazetteer.
- **Red flags:** police surveillance technology from the [EFF Atlas of Surveillance](https://atlasofsurveillance.org/) (license-plate readers, drones, gunshot detection, face recognition, camera registries and more; body-worn cameras are not counted), matched to each government's police department. A department named only for a place that is both a town and a village (or a city and a town with its own police, such as Tonawanda, Newburgh, Poughkeepsie and Lockport) is matched only when the record names the government. License-plate cameras mapped in [OpenStreetMap](https://deflock.org/) (the data DeFlock shows), placed with Census 2024 TIGER boundaries; a camera inside a village is the village's, not the surrounding town's. Any Flock camera is scored, other brands only when the government is the recorded operator. Data center deals and corporate tax breaks from a hand-checked list with sources, \`scripts/ny/corporate-deals.json\`; in New York most are granted by an industrial development agency and are listed under the government whose taxes they cut. Built with \`scripts/common/red-flags.mjs --state ny\`, which must be re-run after \`build-county.mjs\`.
- **Political money:** NY State Board of Elections filings on data.ny.gov (filers and contributions datasets): contributions to candidates for each government's elected offices (judges excluded) over the last four years. Counted: PACs and associations, businesses, unions. Not counted: individuals, candidates and their families, party and candidate committees.

## Known gaps
- **New York City** does not file with the State Comptroller in this format and its campaign money is with the NYC Campaign Finance Board, so it is not included.
- **Villages that dissolved** since 2016 are left out (they are no longer in the Census estimates).
- **Older reports:** ${old.length ? old.join(', ') : 'none'}. These governments have not filed a newer annual report.
- **Red flags** are only as complete as public reporting: the Atlas has far fewer New York records than New Jersey ones, so a government with none listed may still use surveillance tech nobody has reported. The camera map is an OpenStreetMap snapshot from June 1, 2026 (the up-to-date mirrors timed out). The deals list is short and hand-checked; proposed deals that are not approved (the STAMP data center in the Town of Alabama, paused by the July 2026 state moratorium) are left out. 23 Atlas records are not matched: New York City, MTA and county departments, which are not in this dataset, and departments whose name fits two governments.
- **Transparency practices** have not been checked yet, so they are not scored.
- Campaigns that raise little may not itemize contributions, and some local candidates have no filings at all, so a government showing $0 in political money may still have small unreported gifts.
- Filer labels that match no current government (for example "Port Washington,Village", which is not a village, and "Seneca Falls,Village", dissolved in 2012) are left out.
- Dissolved villages still in the Comptroller's files (Cherry Creek, Van Etten, Port Henry, Harrisville, Fort Johnson, Barneveld, South Nyack, Hermon, Morristown, Mastic Beach, Salem) are left out.
`);
console.log(`docs/NY_DATA_STATUS.md: ${covered} governments`);
