#!/usr/bin/env node
// Writes docs/NY_DATA_STATUS.md from the county files in data/real/.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { slugify } from '../lib.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const osc = JSON.parse(readFileSync(join(ROOT, 'data', 'raw', 'ny', 'osc.json'), 'utf8'));
const counties = [...new Set(Object.values(osc).map((g) => g.county))].sort();
const has = (o) => o && typeof o === 'object' && Object.keys(o).length > 0;

const rows = [];
let total = 0;
let covered = 0;
const old = [];
for (const county of counties) {
  const file = join(ROOT, 'data', 'real', `ny-${slugify(county)}.json`);
  const inOsc = Object.values(osc).filter((g) => g.county === county).length;
  if (!existsSync(file)) { rows.push(`| ${county} | not started | | | | | |`); continue; }
  const { towns } = JSON.parse(readFileSync(file, 'utf8'));
  const n = (f) => towns.filter(f).length;
  const types = ['Town', 'Village', 'City'].map((k) => `${n((t) => t.type === k)} ${k.toLowerCase()}${n((t) => t.type === k) === 1 ? '' : 's'}`).filter((s) => !s.startsWith('0 ')).join(', ');
  const years = [...new Set(towns.map((t) => t.fiscalYear))].sort();
  old.push(...towns.filter((t) => t.fiscalYear < 2023).map((t) => `${t.name} (${t.fiscalYear})`));
  total += inOsc;
  covered += towns.length;
  rows.push(`| ${county} | ${towns.length} (${types}) | ${years.length > 2 ? `${years[0]}-${years.at(-1)}` : years.join(', ')} | ${n((t) => typeof t.debt === 'number')} | ${n((t) => Object.values(t.influence || {}).some((v) => v > 0))} of ${n((t) => has(t.influence))} | ${n((t) => has(t.transparency))} |`);
}

writeFileSync(join(ROOT, 'docs', 'NY_DATA_STATUS.md'), `# New York data status

Generated by \`node scripts/ny/status.mjs\`. ${covered} towns, villages and cities loaded (the State Comptroller's files list ${total} governments since 2016, including villages that have since dissolved).

| County | Loaded | Report year(s) | Debt | Political money (with any / loaded) | Transparency |
|---|---|---|---|---|---|
${rows.join('\n')}

## Sources
- **Revenue and spending:** NY Office of the State Comptroller, [Financial Data for Local Governments](https://wwe1.osc.state.ny.us/localgov/findata/financial-data-for-local-governments.cfm): each government's latest Annual Financial Report (actual results, not budgets). Custodial and trust funds, the internal self-insurance fund, transfers between a government's own funds, and bond refinancing are left out because they are not the government's own new money; every build checks that counted plus left-out amounts equal the reported totals.
- **Debt:** the Comptroller's debt data, outstanding at the end of the report year (revenue and tax anticipation notes left out as short-term cash-flow borrowing).
- **Population:** U.S. Census Bureau 2025 population estimates for cities, towns and villages. **Map location:** Census 2024 Gazetteer.
- **Political money:** NY State Board of Elections filings on data.ny.gov (filers and contributions datasets): contributions to candidates for each government's elected offices (judges excluded) over the last four years. Counted: PACs and associations, businesses, unions. Not counted: individuals, candidates and their families, party and candidate committees.

## Known gaps
- **New York City** does not file with the State Comptroller in this format and its campaign money is with the NYC Campaign Finance Board, so it is not included.
- **Villages that dissolved** since 2016 are left out (they are no longer in the Census estimates).
- **Older reports:** ${old.length ? old.join(', ') : 'none'}. These governments have not filed a newer annual report.
- **Transparency practices** have not been checked yet, so they are not scored.
- Campaigns that raise little may not itemize contributions, so a government showing $0 in political money may still have small unreported gifts.
`);
console.log(`docs/NY_DATA_STATUS.md: ${covered} governments`);
