#!/usr/bin/env node
// Writes docs/VA_DATA_STATUS.md from the county and city files in data/real/.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { totals, scoreTown } from '../../js/engine/scoring.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'data', 'real');
const apa = JSON.parse(readFileSync(join(ROOT, 'data', 'raw', 'va', 'apa.json'), 'utf8'));
const towns = readdirSync(OUT).filter((f) => /^va-.*\.json$/.test(f)).flatMap((f) => JSON.parse(readFileSync(join(OUT, f), 'utf8')).towns);
const years = Object.keys(apa).sort();
const latest = years.at(-1);
const median = (a) => a.sort((x, y) => x - y)[a.length >> 1];
const money = (n) => `$${Math.round(n).toLocaleString('en-US')}`;

const rows = ['County', 'City', 'Town'].map((kind) => {
  const g = towns.filter((t) => t.type === kind);
  const pol = g.filter((t) => t.influence);
  const withMoney = g.filter((t) => Object.values(t.influence || {}).some((v) => v > 0));
  const fy = [...new Set(g.map((t) => t.fiscalYear))].sort();
  return { kind, n: g.length, fy, debt: g.filter((t) => typeof t.debt === 'number').length, pol: pol.length, withMoney: withMoney.length,
    score: Math.round(median(g.map((t) => scoreTown(t).score))), admin: Math.round(median(g.map((t) => totals(t).adminShare)) * 100) };
});
const listed = new Set(towns.map((t) => `${t.type}|${t.name.replace(/^(City|Town) of /, '').replace(/ County$/, '')}`));
const all = new Set(Object.values(apa).flatMap((y) => Object.keys(y)));
const missing = [...all].filter((k) => !listed.has(k.replace('&', 'and')) && !listed.has(k)).map((k) => k.replace('|', ' of ').replace(/^County of (.+)$/, '$1 County')).sort();
const older = towns.filter((t) => String(t.fiscalYear) !== latest).map((t) => `${t.name} (FY ${t.fiscalYear})`).sort();
const polTotal = towns.reduce((a, t) => a + Object.values(t.influence || {}).reduce((x, y) => x + y, 0), 0);
const business = towns.reduce((a, t) => a + (t.influence?.developerContributions || 0), 0);

writeFileSync(join(ROOT, 'docs', 'VA_DATA_STATUS.md'), `# Virginia data status

Generated by \`node scripts/va/status.mjs\`. ${towns.length} localities loaded. Virginia has no townships: counties and independent cities are the local governments for everyone, and towns are a second layer inside counties. Each county's file holds the county and its towns; each independent city has its own file.

| Type | Loaded | Fiscal year(s) | Debt | Political money (scored / with money) | Median score | Median overhead |
|---|---|---|---|---|---|---|
${rows.map((r) => `| ${r.kind === 'City' ? 'Independent cities' : `${r.kind === 'County' ? 'Counties' : 'Towns'}`} | ${r.n} | ${r.fy.join(', ')} | ${r.debt} | ${r.pol} / ${r.withMoney} | ${r.score} | ${r.admin}% |`).join('\n')}

## Sources
- **Revenue, spending and debt:** VA Auditor of Public Accounts, [Comparative Report of Local Government Revenues and Expenditures](https://www.apa.virginia.gov/local-government/reports?type=comparative-reports), FY ${years[0]}-${latest} (Excel). Actual results each locality transmits from its audited financial statements: local revenue by source, aid from the Commonwealth and federal government, operations by function, capital projects, debt service, enterprise activities and gross debt. Every locality's revenue and operations reconcile to the Auditor's own summary (Exhibit A).
- **Political money:** VA Department of Elections [monthly bulk campaign finance files](https://apps.elections.virginia.gov/SBE_CSV/CF/): local candidates' reports and itemized receipts.
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer.

## How Virginia differs
- **Counties and cities run schools.** School division operations and school construction are on county and city reports, shown as schools and left out of the services and overhead shares, as in Connecticut and Massachusetts. Towns do not run schools.
- **Judicial administration counts as overhead.** Counties and cities pay for courts, the Commonwealth's attorney and clerks; these count as overhead, as does community development.
- **Business money is allowed.** Virginia lets businesses give to candidates, so political money counts businesses as well as unions and PACs: ${money(business)} of the ${money(polTotal)} counted came from businesses.

## Known gaps
- **Not reported to the Auditor for FY ${years[0]}-${latest}:** ${missing.length ? missing.join(', ') : 'none'}. They are not listed.
- **Older year used** because FY ${latest} has not been reported yet: ${older.length ? older.join(', ') : 'none'}.
- **Small towns** (most of Virginia's 95 incorporated towns) are not required to file the comparative report and are not listed.
- **Political money:** local candidates are placed by their committee's filing address (ZIP code area, or the mailing city for PO boxes), so a few may be assigned to a neighbouring locality; committees whose locality cannot be found are left out. "Business" means a non-individual contributor not recognized as a union, PAC or campaign committee, so it may include some advocacy groups.
- **Transparency practices** have not been checked yet, so they are not scored.
`);
console.log(`docs/VA_DATA_STATUS.md: ${towns.length} localities`);
