#!/usr/bin/env node
// Writes docs/RI_DATA_STATUS.md from the county files in data/real/.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCSV, slugify } from '../lib.mjs';
import { totals, scoreTown } from '../../js/engine/scoring.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const pop = parseCSV(readFileSync(join(ROOT, 'data', 'raw', 'ri', 'popest.csv'), 'latin1'));
const counties = pop.filter((r) => r.sumlev === '050').map((r) => r.name.replace(/ County$/, '')).sort();
const rows = [];
const older = [];
const admin = [];
const scores = [];
let covered = 0;
let withMoney = 0;
let polTotal = 0;
let since = '';
let latest = 0;
for (const county of counties) {
  const file = join(ROOT, 'data', 'real', `ri-${slugify(county)}.json`);
  if (!existsSync(file)) { rows.push(`| ${county} | not started | | |`); continue; }
  const { towns } = JSON.parse(readFileSync(file, 'utf8'));
  const cities = towns.filter((t) => t.type === 'City').length;
  const types = [[towns.length - cities, 'town'], [cities, 'city']].filter(([c]) => c)
    .map(([c, k]) => (k === 'city' ? `${c} ${c === 1 ? 'city' : 'cities'}` : `${c} town${c === 1 ? '' : 's'}`)).join(', ');
  for (const t of towns) {
    latest = Math.max(latest, t.fiscalYear);
    admin.push(totals(t).adminShare);
    scores.push(scoreTown(t).score);
    const v = Object.values(t.influence || {}).reduce((a, b) => a + b, 0);
    if (v > 0) withMoney++;
    polTotal += v;
    since ||= (t.sources.find((x) => /Board of Elections/.test(x.label))?.label.match(/since (\d{4})/) || [])[1] || '';
  }
  older.push(...towns.map((t) => [t.name, t.fiscalYear]));
  covered += towns.length;
  const fy = [...new Set(towns.map((t) => t.fiscalYear))].sort();
  rows.push(`| ${county} | ${towns.length} (${types}) | ${fy.join(', ')} | ${towns.filter((t) => t.influence).length} |`);
}
const median = (a) => a.sort((x, y) => x - y)[a.length >> 1];
const behind = older.filter(([, y]) => y < latest).map(([n, y]) => `${n} (FY ${y})`);
writeFileSync(join(ROOT, 'docs', 'RI_DATA_STATUS.md'), `# Rhode Island data status

Generated by \`node scripts/ri/status.mjs\`. ${covered} of 39 cities and towns loaded, grouped by the state's five counties (Rhode Island has no county governments, but the Census still uses them).

| County | Loaded | Fiscal year(s) | Political money |
|---|---|---|---|
${rows.join('\n')}

## Sources
- **Revenue and spending:** RI Division of Municipal Finance, [Municipal Transparency Portal](https://municipalfinance.ri.gov/municipal-transparency) ("MTP All Data"). Audited actual results under the state's uniform chart of accounts, FY 2016 on: revenue by account and spending by department. The site is behind a browser check, so \`download.mjs\` uses Playwright when it is installed, or the file can be saved by hand.
- **Political money:** RI Board of Elections, [Campaign Finance Electronic Reporting & Tracking System](https://ricampaignfinance.com/RIPublic/Contributions.aspx) (ERTS): PAC contributions, and filers for local and state office.
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer.

## How Rhode Island differs
- **Schools are the town's appropriation.** School departments and regional school districts report separately, and state school aid goes to them directly. Reports show the town's appropriation to its schools, left out of the services and overhead shares as in Connecticut and Massachusetts.
- **Central costs are spread.** Retiree health (OPEB), and the benefits, pension contributions, insurance and claims many towns record under general government for the whole workforce, are spread across the town's own departments by size. Capital outlays recorded under general government are spread across all departments. The median town then spends ${Math.round(median(admin) * 100)}% of its non-school budget on general government (NJ, NY and PA are 15-17%).
- **Fiscal health is not scored.** Debt outstanding is not reported to the state in a loadable form, so only services, overhead and political money are scored. That leaves fewer parts, and scores run higher than in states where debt is scored (median ${Math.round(median(scores))}).

## Known gaps
- **Political money covers local candidates and party committees.** All Rhode Island candidates file with the Board of Elections. Counted since ${since}: PAC contributions (many from unions) to candidates for mayor or administrator, council, school committee and other town offices, placed in a town by their filing address, and to party city and town committees. Corporate contributions to candidates are banned in Rhode Island. A filer keeps one account across offices, so local candidates who have also run for state office are left out; their money cannot be told apart. ${withMoney} of ${covered} towns had PAC money, $${Math.round(polTotal).toLocaleString('en-US')} in all.
- **Debt and transparency practices** are not loaded, so fiscal health and transparency are not scored.
- **Older year used** because FY ${latest} is not on the portal yet: ${behind.length ? behind.join(', ') : 'none'}.
- Other financing sources and uses (bond proceeds, transfers) are left out. Fire districts, water and sewer authorities and other independent districts are separate and not included.
`);
console.log(`docs/RI_DATA_STATUS.md: ${covered} cities and towns`);
