#!/usr/bin/env node
// Writes docs/FL_DATA_STATUS.md from the county files in data/real/ and the last
// `build-county.mjs --all` report.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { totals, scoreTown } from '../../js/engine/scoring.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'data', 'real');
const RAW = join(ROOT, 'data', 'raw', 'fl');
const report = JSON.parse(readFileSync(join(RAW, 'build-report.json'), 'utf8'));
const index = JSON.parse(readFileSync(join(RAW, 'edr-index.json'), 'utf8'));
const towns = readdirSync(OUT).filter((f) => /^fl-.*\.json$/.test(f)).flatMap((f) => JSON.parse(readFileSync(join(OUT, f), 'utf8')).towns);
const median = (a) => a.sort((x, y) => x - y)[a.length >> 1];
const years = [...new Set(towns.map((t) => t.fiscalYear))].sort();

const kinds = ['County', 'Consolidated government', 'City', 'Town', 'Village'];
const label = { County: 'Counties', 'Consolidated government': 'Consolidated (Jacksonville-Duval)', City: 'Cities', Town: 'Towns', Village: 'Villages' };
const rows = kinds.map((kind) => {
  const g = towns.filter((t) => t.type === kind);
  return { kind, n: g.length, fy: years.map((y) => `${y}: ${g.filter((t) => t.fiscalYear === y).length}`).join(', '),
    score: g.length ? Math.round(median(g.map((t) => scoreTown(t).score))) : '-', admin: g.length ? `${Math.round(median(g.map((t) => totals(t).adminShare)) * 100)}%` : '-' };
});

writeFileSync(join(ROOT, 'docs', 'FL_DATA_STATUS.md'), `# Florida data status

Generated by \`node scripts/fl/status.mjs\`. ${towns.length} of the ${index.length} governments EDR lists are loaded. Florida has no townships: counties serve everyone, and cities, towns and villages are a second layer inside them; Jacksonville is consolidated with Duval County. Public schools are run by separate school districts. Each county's file holds the county and the municipalities whose people mostly live in it.

| Type | Loaded | Fiscal year used (count) | Median score | Median overhead |
|---|---|---|---|---|
${rows.filter((r) => r.n).map((r) => `| ${label[r.kind]} | ${r.n} | ${r.fy} | ${r.score} | ${r.admin} |`).join('\n')}

## Sources
- **Revenue and spending:** FL Office of Economic and Demographic Research, Expenditures and Revenues Reported by Florida's [County](https://www.edr.state.fl.us/Content/local-government/data/revenues-expenditures/cntyfiscal.cfm) and [Municipal](https://www.edr.state.fl.us/Content/local-government/data/revenues-expenditures/munifiscal.cfm) Governments: each government's Annual Financial Report to the Department of Financial Services, by Uniform Accounting System account code and fund type, FY 2008 on. Governmental and enterprise funds are counted; internal service, fiduciary (pension, trust, custodial) and component unit columns, transfers, borrowing and other financing are left out.
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer.

## How Florida differs
- **Schools are separate.** School districts are their own governments, so county and municipal reports do not include schools.
- **Counties include the constitutional officers** (sheriff, clerk of court, property appraiser, tax collector and supervisor of elections).
- **Enterprise funds use accrual accounting**, so utility spending includes depreciation rather than capital purchases, and interest on enterprise debt is part of enterprise expenses.
- **Debt outstanding is not in the EDR data**, so fiscal health is not scored.
- **Political money is not scored.** County candidates file campaign reports with the county supervisor of elections and municipal candidates with the city clerk; there is no statewide source for local candidates.

## Known gaps
- **No Annual Financial Report in the EDR data since FY 2022 (left out, ${report.notFiled.length}):** ${report.notFiled.length ? report.notFiled.join(', ') : 'none'}.
- **Reports since FY 2022 left out because revenue and spending are more than four times apart** (an entry error or a part left out; ${report.inconsistent.length}): ${report.inconsistent.length ? report.inconsistent.join(', ') : 'none'}.
- **Not matched to Census geography:** ${report.skipped.length ? report.skipped.join(', ') : 'none'}.
- **Older year used** because the latest year is empty or inconsistent: ${report.older.length ? report.older.join(', ') : 'none'}.
- **Transparency practices** have not been checked yet, so they are not scored.
`);
console.log(`docs/FL_DATA_STATUS.md: ${towns.length} governments`);
