#!/usr/bin/env node
// Writes docs/NC_DATA_STATUS.md from the county files in data/real/ and the last
// `build-county.mjs --all` report.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { totals, scoreTown } from '../../js/engine/scoring.js';
import { YEARS } from './download.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'data', 'real');
const report = JSON.parse(readFileSync(join(ROOT, 'data', 'raw', 'nc', 'build-report.json'), 'utf8'));
const towns = readdirSync(OUT).filter((f) => /^nc-.*\.json$/.test(f)).flatMap((f) => JSON.parse(readFileSync(join(OUT, f), 'utf8')).towns);
const median = (a) => a.sort((x, y) => x - y)[a.length >> 1];
const money = (n) => `$${Math.round(n).toLocaleString('en-US')}`;
const fixName = (s) => s.replace(/^([A-Z' .-]+) (TOWN|CITY|VILLAGE)$/, (m, n, k) => `${k[0]}${k.slice(1).toLowerCase()} of ${n.toLowerCase().replace(/\b[a-z]/g, (c) => c.toUpperCase())}`);

const rows = ['County', 'City', 'Town', 'Village'].map((kind) => {
  const g = towns.filter((t) => t.type === kind);
  const withMoney = g.filter((t) => Object.values(t.influence || {}).some((v) => v > 0));
  const fy = YEARS.map((y) => `${y}: ${g.filter((t) => t.fiscalYear === y).length}`).join(', ');
  return { kind, n: g.length, fy, pol: g.filter((t) => t.influence).length, withMoney: withMoney.length,
    score: Math.round(median(g.map((t) => scoreTown(t).score))), admin: Math.round(median(g.map((t) => totals(t).adminShare)) * 100) };
});
const label = { County: 'Counties', City: 'Cities', Town: 'Towns', Village: 'Villages' };
const polTotal = towns.reduce((a, t) => a + Object.values(t.influence || {}).reduce((x, y) => x + y, 0), 0);
const union = towns.reduce((a, t) => a + (t.influence?.unionContributions || 0), 0);
const imputed = [...new Set(report.imputed.map(fixName))].sort();
const incomplete = [...new Set(report.incomplete.map(fixName))].sort();

writeFileSync(join(ROOT, 'docs', 'NC_DATA_STATUS.md'), `# North Carolina data status

Generated by \`node scripts/nc/status.mjs\`. ${towns.length} governments loaded. North Carolina has no townships: counties serve everyone, and cities, towns and villages are a second layer inside them. Each county's file holds the county and the municipalities whose people mostly live in it.

| Type | Loaded | Fiscal year used (count) | Political money (scored / with money) | Median score | Median overhead |
|---|---|---|---|---|---|
${rows.map((r) => `| ${label[r.kind]} | ${r.n} | ${r.fy} | ${r.pol} / ${r.withMoney} | ${r.score} | ${r.admin}% |`).join('\n')}

## Sources
- **Revenue, spending and debt:** each government's Annual Financial Information Report (AFIR) to the Local Government Commission, which North Carolina collects on the Census Bureau's template, as published in the Census Bureau's [Annual Survey of State and Local Government Finances individual unit files](https://www.census.gov/programs-surveys/gov-finances.html), FY ${YEARS[0]}-${YEARS.at(-1)}: taxes, charges, aid, spending by function (operations, construction, equipment), interest, principal repaid and debt outstanding, for all funds. ${YEARS[0]} is a Census of Governments year covering every government; later years cover a sample, so each government's latest reported year is used. The Treasurer's own AFIR site could not be reached (its server sends an incomplete certificate chain).
- **Political money:** NC State Board of Elections [campaign finance transaction search](https://cf.ncsbe.gov/CFTxnLkup/): contributions from political committees and non-profits to candidates for county and municipal office.
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer.

## How North Carolina differs
- **Counties fund schools.** The Census counts each county's public school system as part of the county, so school operations and construction are on county reports, shown as schools and left out of the services and overhead shares, as in Connecticut, Massachusetts and Virginia. Municipalities do not run schools.
- **Payments to other governments are left out.** The receiving government reports that spending; in FY 2024 some counties (Wake and Union among them) also report their school system's funding there, which would count it twice.
- **Corporate money is banned.** North Carolina bars corporations from contributing to candidates, so political money counts PACs, unions and other organizations: ${money(union)} of the ${money(polTotal)} counted came from unions.

## Known gaps
- **Estimated by the Census, not filed (left out, ${imputed.length}):** ${imputed.length ? imputed.join(', ') : 'none'}.
- **Incomplete in the Census files (only debt or ABC board figures; left out, ${incomplete.length}):** ${incomplete.length ? incomplete.join(', ') : 'none'}.
- **No longer listed by the Census:** ${report.skipped.length ? report.skipped.map((s) => fixName(s.replace(/: .*/, ''))).join(', ') : 'none'}.
- **Older year used** because the latest sampled year was estimated or incomplete: ${report.older.length ? report.older.join(', ') : 'none'}.
- **Political money:** candidates are placed by office and their committee's filing address (municipal candidates by mailing city or the municipality their committee is named for; county candidates by ZIP code area), so a few may be assigned to a neighbouring government. Municipal candidates whose municipality cannot be found are left out.
- **Transparency practices** have not been checked yet, so they are not scored.
`);
console.log(`docs/NC_DATA_STATUS.md: ${towns.length} governments`);
