#!/usr/bin/env node
// Writes docs/NH_DATA_STATUS.md from the county files in data/real/ and the last
// `build-county.mjs --all` report.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { totals, scoreTown } from '../../js/engine/scoring.js';
import { YEARS } from '../common/census-units.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'data', 'real');
const report = JSON.parse(readFileSync(join(ROOT, 'data', 'raw', 'nh', 'build-report.json'), 'utf8'));
const towns = readdirSync(OUT).filter((f) => /^nh-.*\.json$/.test(f)).flatMap((f) => JSON.parse(readFileSync(join(OUT, f), 'utf8')).towns);
const median = (a) => a.sort((x, y) => x - y)[a.length >> 1];

const rows = ['County', 'City', 'Town'].map((kind) => {
  const g = towns.filter((t) => t.type === kind);
  const fy = YEARS.map((y) => `${y}: ${g.filter((t) => t.fiscalYear === y).length}`).join(', ');
  return { kind, n: g.length, fy, score: Math.round(median(g.map((t) => scoreTown(t).score))), admin: Math.round(median(g.map((t) => totals(t).adminShare)) * 100) };
});
const label = { County: 'Counties', City: 'Cities', Town: 'Towns' };
const imputed = [...new Set(report.imputed)].sort();
const incomplete = [...new Set(report.incomplete)].sort();
const adjusted = towns.filter((t) => t.notes.some((n) => n.includes('Only the') && n.includes('own share')));

writeFileSync(join(ROOT, 'docs', 'NH_DATA_STATUS.md'), `# New Hampshire data status

Generated by \`node scripts/nh/status.mjs\`. ${towns.length} governments loaded. New Hampshire's 221 towns and 13 cities are its main local governments; its ten counties run nursing homes, jails, sheriffs and county attorneys. Most public schools are run by separate school districts, but several cities run their own school departments. Each county's file holds the county and its cities and towns.

| Type | Loaded | Fiscal year used (count) | Median score | Median overhead |
|---|---|---|---|---|
${rows.filter((r) => r.n).map((r) => `| ${label[r.kind]} | ${r.n} | ${r.fy} | ${r.score} | ${r.admin}% |`).join('\n')}

## Sources
- **Revenue, spending and debt:** what each government reported to the U.S. Census Bureau's [Annual Survey of State and Local Government Finances](https://www.census.gov/programs-surveys/gov-finances.html) (individual unit files), FY ${YEARS[0]}-${YEARS.at(-1)}, with the same mapping as the Carolinas and Delaware. The Census counts New Hampshire's towns as township governments. ${YEARS[0]} is a Census of Governments year covering every government; later years cover a sample, so each government's latest reported year is used. The Department of Revenue Administration collects each town's annual financial report (MS-535) but publishes them only as individual documents, and its website refused connections from the build environment.
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer (county subdivisions).

## How New Hampshire differs
- **One tax bill, several governments.** Each town and city collects the whole property tax bill, including the shares for the school district, the county and the state education tax, and pays them over. ${adjusted.length} of the ${towns.length - rows[0].n} cities and towns reported the whole levy to the Census as their own property tax. For those, only the town's own share is counted: what its spending needed beyond its other revenue, which is how the Department of Revenue Administration sets the town rate. That also means they show no surplus or deficit for the year. Each affected town's report says so and gives the amounts.
- **City school departments.** Cities such as Manchester, Nashua, Dover, Rochester and Somersworth run their own schools, so school spending is part of their reports; school spending is left out of the services and overhead shares, as in Connecticut and Massachusetts.
- **Payments to other governments are left out**, as in the Carolinas and Delaware.

## Known gaps
- **Political money is not scored.** Town and city candidates file with their clerk, not the state. County candidates file with the Secretary of State, whose campaign finance system refused connections from the build environment.
- **Estimated by the Census, not reported (left out, ${imputed.length}):** ${imputed.length ? imputed.join(', ') : 'none'}. This includes Concord, Portsmouth and Rockingham County.
- **Incomplete in the Census files (only debt or a few figures, or spending under a quarter of revenue; left out, ${incomplete.length}):** ${incomplete.length ? incomplete.join(', ') : 'none'}.
- **Older year used** because the latest sampled year was estimated or incomplete: ${report.older.length ? report.older.join(', ') : 'none'}.
- **Not in the Census files:** unincorporated places (locations, grants and purchases, mostly in Coos County) have no government of their own.
- **Transparency practices** have not been checked yet, so they are not scored.
`);
console.log(`docs/NH_DATA_STATUS.md: ${towns.length} governments`);
