#!/usr/bin/env node
// Writes docs/SC_DATA_STATUS.md from the county files in data/real/ and the last
// `build-county.mjs --all` report.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { totals, scoreTown } from '../../js/engine/scoring.js';
import { YEARS } from '../common/census-units.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'data', 'real');
const report = JSON.parse(readFileSync(join(ROOT, 'data', 'raw', 'sc', 'build-report.json'), 'utf8'));
const towns = readdirSync(OUT).filter((f) => /^sc-.*\.json$/.test(f)).flatMap((f) => JSON.parse(readFileSync(join(OUT, f), 'utf8')).towns);
const median = (a) => a.sort((x, y) => x - y)[a.length >> 1];
const money = (n) => `$${Math.round(n).toLocaleString('en-US')}`;
const fixName = (s) => s.replace(/^([A-Z' .-]+) (TOWN|CITY)$/, (m, n, k) => `${k[0]}${k.slice(1).toLowerCase()} of ${n.toLowerCase().replace(/\b[a-z]/g, (c) => c.toUpperCase())}`);

const rows = ['County', 'City', 'Town'].map((kind) => {
  const g = towns.filter((t) => t.type === kind);
  const withMoney = g.filter((t) => Object.values(t.influence || {}).some((v) => v > 0));
  const fy = YEARS.map((y) => `${y}: ${g.filter((t) => t.fiscalYear === y).length}`).join(', ');
  return { kind, n: g.length, fy, pol: g.filter((t) => t.influence).length, withMoney: withMoney.length,
    score: Math.round(median(g.map((t) => scoreTown(t).score))), admin: Math.round(median(g.map((t) => totals(t).adminShare)) * 100) };
});
const label = { County: 'Counties', City: 'Cities', Town: 'Towns' };
const polTotal = towns.reduce((a, t) => a + Object.values(t.influence || {}).reduce((x, y) => x + y, 0), 0);
const business = towns.reduce((a, t) => a + (t.influence?.developerContributions || 0), 0);
const imputed = [...new Set(report.imputed.map(fixName))].sort();
const incomplete = [...new Set(report.incomplete.map(fixName))].sort();

writeFileSync(join(ROOT, 'docs', 'SC_DATA_STATUS.md'), `# South Carolina data status

Generated by \`node scripts/sc/status.mjs\`. ${towns.length} governments loaded. South Carolina has no townships: counties serve everyone, and cities and towns are a second layer inside them. Public schools are run by separate school districts. Each county's file holds the county and the municipalities whose people mostly live in it.

| Type | Loaded | Fiscal year used (count) | Political money (scored / with money) | Median score | Median overhead |
|---|---|---|---|---|---|
${rows.map((r) => `| ${label[r.kind]} | ${r.n} | ${r.fy} | ${r.pol} / ${r.withMoney} | ${r.score} | ${r.admin}% |`).join('\n')}

## Sources
- **Revenue, spending and debt:** what each government reported to the U.S. Census Bureau's [Annual Survey of State and Local Government Finances](https://www.census.gov/programs-surveys/gov-finances.html) (individual unit files), FY ${YEARS[0]}-${YEARS.at(-1)}: taxes, charges, aid, spending by function (operations, construction, equipment), interest, principal repaid and debt outstanding, for all funds. ${YEARS[0]} is a Census of Governments year covering every government; later years cover a sample, so each government's latest reported year is used. The state Revenue and Fiscal Affairs Office's Local Government Finance Report was not used: it adds each county's cities together and leaves out utilities.
- **Political money:** SC State Ethics Commission [public contribution search](https://ethicsfiling.sc.gov/public/campaign-reports/contributions): group (non-individual) contributions to candidates for county and municipal office, placed by the office sought.
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer.

## How South Carolina differs
- **Schools are separate.** School districts are their own governments, so county and municipal reports do not include schools.
- **Payments to other governments are left out**, as in North Carolina: the receiving government reports that spending.
- **Business money is allowed.** South Carolina lets businesses give to candidates, so political money counts businesses as well as unions and PACs: ${money(business)} of the ${money(polTotal)} counted came from businesses.

## Known gaps
- **Estimated by the Census, not reported (left out, ${imputed.length}):** ${imputed.length ? imputed.join(', ') : 'none'}.
- **Incomplete in the Census files (only debt or a few figures, or spending under a quarter of revenue; left out, ${incomplete.length}):** ${incomplete.length ? incomplete.join(', ') : 'none'}.
- **No longer listed by the Census:** ${report.skipped.length ? report.skipped.map((s) => fixName(s.replace(/: .*/, ''))).join(', ') : 'none'}.
- **Older year used** because the latest sampled year was estimated or incomplete: ${report.older.length ? report.older.join(', ') : 'none'}.
- **Political money:** scored where a local candidate filed with the Ethics Commission since ${new Date().getFullYear() - 3}. Solicitors (judicial circuits), school boards and special purpose districts are left out. "Business" means a group contributor not recognized as a union, PAC or campaign committee, so it may include some advocacy groups.
- **Transparency practices** have not been checked yet, so they are not scored.
`);
console.log(`docs/SC_DATA_STATUS.md: ${towns.length} governments`);
