#!/usr/bin/env node
// Writes docs/NJ_DATA_STATUS.md from the county files in data/real/.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { NJ_COUNTIES } from './ufb-map.mjs';
import { slugify } from '../lib.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const ufbPath = join(ROOT, 'data', 'raw', 'nj', 'ufb.json');
const filed = existsSync(ufbPath)
  ? Object.fromEntries(NJ_COUNTIES.map((c) => [c, JSON.parse(readFileSync(ufbPath, 'utf8'))['2026'].filter((r) => r['|County'] === c).length]))
  : {};

const has = (o) => o && typeof o === 'object' && Object.keys(o).length > 0;
const rows = [];
let total = 0;
let covered = 0;
for (const county of NJ_COUNTIES) {
  const file = join(ROOT, 'data', 'real', `nj-${slugify(county)}.json`);
  if (!existsSync(file)) { rows.push(`| ${county} | not started | | | | | |`); continue; }
  const { towns } = JSON.parse(readFileSync(file, 'utf8'));
  const n = (f) => towns.filter(f).length;
  const years = [...new Set(towns.map((t) => t.fiscalYear))].sort().join(', ');
  total += filed[county] || towns.length;
  covered += towns.length;
  rows.push(`| ${county} | ${towns.length} of ${filed[county] ?? '?'} | ${years} | ${n((t) => has(t.spending))} | ${n((t) => typeof t.debt === 'number')} | ${n((t) => has(t.influence))} | ${n((t) => has(t.transparency))} |`);
}

writeFileSync(join(ROOT, 'docs', 'NJ_DATA_STATUS.md'), `# New Jersey data status

Generated by \`node scripts/nj/status.mjs\`. ${covered} of ${total} municipalities loaded.

| County | Towns loaded | Budget year(s) | Budget | Net debt | Political money | Transparency |
|---|---|---|---|---|---|---|
${rows.join('\n')}

## Sources
- **Budget, net debt, population:** NJ Division of Local Government Services, [User Friendly Budget Database](https://datahub.dca.nj.gov/datasets/user-friendly-budget-database). Each town's latest filed adopted budget (2026, or 2025 if the 2026 filing is not in the database yet). Category totals are checked against each filing's own totals during the build.
- **Map location:** U.S. Census Bureau 2024 Gazetteer, county subdivisions.

## Known gaps
- **Political money** (NJ ELEC filings) is not loaded yet, so it is not scored.
- **Transparency practices** have not been checked town by town yet, so they are not scored.
- The state budget format does not separate outside legal and engineering costs from general government, so "consultants" is not broken out for NJ towns.
- Towns without a usable filing in the database are left out rather than estimated. The build prints any it skips.
`);
console.log(`docs/NJ_DATA_STATUS.md: ${covered} of ${total} towns`);
