#!/usr/bin/env node
// Writes docs/NJ_DATA_STATUS.md from the county files in data/real/.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { NJ_COUNTIES } from './ufb-map.mjs';
import { slugify } from '../lib.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const ufbPath = join(ROOT, 'data', 'raw', 'nj', 'ufb.json');
const filed = existsSync(ufbPath)
  ? Object.fromEntries(NJ_COUNTIES.map((c) => [c, JSON.parse(readFileSync(ufbPath, 'utf8'))['2026'].filter((r) => r['|County'] === c).length]))
  : null; // without the raw workbook, fall back to the last published counts below
const LAST_FILED = { Atlantic: 23, Bergen: 70, Burlington: 40, Camden: 36, 'Cape May': 16, Cumberland: 14, Essex: 22, Gloucester: 24, Hudson: 12, Hunterdon: 26, Mercer: 12, Middlesex: 25, Monmouth: 53, Morris: 39, Ocean: 33, Passaic: 16, Salem: 15, Somerset: 21, Sussex: 24, Union: 21, Warren: 22 };
const filedIn = (c) => (filed ? filed[c] : LAST_FILED[c]);

const has = (o) => o && typeof o === 'object' && Object.keys(o).length > 0;
const rows = [];
let total = 0;
let covered = 0;
for (const county of NJ_COUNTIES) {
  const file = join(ROOT, 'data', 'real', `nj-${slugify(county)}.json`);
  if (!existsSync(file)) { rows.push(`| ${county} | not started | | | | | | |`); continue; }
  const { towns } = JSON.parse(readFileSync(file, 'utf8'));
  const n = (f) => towns.filter(f).length;
  const years = [...new Set(towns.map((t) => t.fiscalYear))].sort().join(', ');
  total += filedIn(county) || towns.length;
  covered += towns.length;
  rows.push(`| ${county} | ${towns.length} of ${filedIn(county) ?? '?'} | ${years} | ${n((t) => has(t.spending))} | ${n((t) => typeof t.debt === 'number')} | ${n((t) => has(t.influence))} | ${n((t) => has(t.transparency))} | ${n((t) => t.redFlags?.length)} of ${n((t) => Array.isArray(t.redFlags))} |`);
}

writeFileSync(join(ROOT, 'docs', 'NJ_DATA_STATUS.md'), `# New Jersey data status

Generated by \`node scripts/nj/status.mjs\`. ${covered} of ${total} municipalities loaded.

| County | Towns loaded | Budget year(s) | Budget | Net debt | Political money | Transparency | Red flags (towns flagged of checked) |
|---|---|---|---|---|---|---|---|
${rows.join('\n')}

## Sources
- **Budget, net debt, population:** NJ Division of Local Government Services, [User Friendly Budget Database](https://datahub.dca.nj.gov/datasets/user-friendly-budget-database). Each town's latest filed adopted budget (2026, or 2025 if the 2026 filing is not in the database yet). Category totals are checked against each filing's own totals during the build.
- **Map location:** U.S. Census Bureau 2024 Gazetteer, county subdivisions.
- **Red flags:** police surveillance technology from the [EFF Atlas of Surveillance](https://atlasofsurveillance.org/) (license-plate readers, drones, gunshot detection, face recognition, camera registries, predictive policing; body-worn cameras are not counted), matched to each town's police department. License-plate cameras mapped in [OpenStreetMap](https://deflock.org/) (the data DeFlock shows), placed in towns with Census 2024 TIGER boundaries; any Flock camera is scored, other brands only when the town is the recorded operator. Data center deals and corporate lobbying from a hand-checked list with sources, \`scripts/nj/corporate-deals.json\`. Built with \`scripts/nj/red-flags.mjs\`, which must be re-run after \`build-county.mjs\`.
- **Political money:** NJ ELEC [contribution search](https://www.njelecefilesearch.com/SearchContributionToEntity): itemized contributions to candidates for each town's municipal office and mayor over the last four years. Counted: PACs, businesses and unions. Not counted: individuals, candidates' own committees, and party committees (also when a party is filed under a business type). Built with \`scripts/nj/fetch-elec.mjs\` and \`scripts/nj/elec-map.mjs\`.

## Known gaps
- **Political money** covers municipal candidates only. Small campaigns can file without itemizing, so a town showing $0 may still have unreported small contributions. Contractor pay-to-play disclosures (ELEC Form BE) are not loaded yet: that search was refused from this environment.
- **Red flags** are only as complete as public reporting. A town with none listed may still use surveillance tech nobody has reported, and most records give no dollar amount, so red flags are scored by count rather than as spending. The data center list is short and hand-checked; proposed deals that were later dropped or banned (Andover, Logan, Holmdel) are left out. Corporate tax abatements in general (long-term PILOTs for warehouses, housing and redevelopment) are not loaded yet: the state has no central, machine-readable list. 11 Atlas records were not matched because the name fits two towns (e.g. Chester Borough and Chester Township) or Atlas lists the wrong county.
- **Transparency practices** have not been checked town by town yet, so they are not scored.
- The state budget format does not separate outside legal and engineering costs from general government, so "consultants" is not broken out for NJ towns.
- Towns without a usable filing in the database are left out rather than estimated. The build prints any it skips.
`);
console.log(`docs/NJ_DATA_STATUS.md: ${covered} of ${total} towns`);
