#!/usr/bin/env node
// Writes docs/CT_DATA_STATUS.md from the planning-region files in data/real/.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCSV, slugify } from '../lib.mjs';
import { totals } from '../../js/engine/scoring.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const pop = parseCSV(readFileSync(join(ROOT, 'data', 'raw', 'ct', 'popest.csv'), 'latin1'));
const regions = pop.filter((r) => r.sumlev === '050').map((r) => r.name.replace(/ Planning Region$/, '')).sort();
const rows = [];
const older = [];
const notItemized = [];
const admin = [];
let covered = 0;
for (const region of regions) {
  const file = join(ROOT, 'data', 'real', `ct-${slugify(region)}.json`);
  if (!existsSync(file)) { rows.push(`| ${region} | not started | | |`); continue; }
  const { towns } = JSON.parse(readFileSync(file, 'utf8'));
  const n = (f) => towns.filter(f).length;
  const types = ['Town', 'City', 'Borough'].map((k) => [k, n((t) => t.type === k)]).filter(([, c]) => c)
    .map(([k, c]) => (k === 'City' ? `${c} ${c === 1 ? 'city' : 'cities'}` : `${c} ${k.toLowerCase()}${c === 1 ? '' : 's'}`)).join(', ');
  const years = [...new Set(towns.map((t) => t.fiscalYear))].sort();
  older.push(...towns.filter((t) => t.fiscalYear < 2023 && !t.spending.otherSpending).map((t) => `${t.name} (FY ${t.fiscalYear})`));
  notItemized.push(...towns.filter((t) => t.spending.otherSpending).map((t) => t.name));
  for (const t of towns) if (!t.spending.otherSpending) admin.push(totals(t).adminShare);
  covered += towns.length;
  rows.push(`| ${region} | ${towns.length} (${types}) | ${years.join(', ')} | ${n((t) => typeof t.debt === 'number')} |`);
}
admin.sort((a, b) => a - b);
const median = Math.round(admin[admin.length >> 1] * 100);
writeFileSync(join(ROOT, 'docs', 'CT_DATA_STATUS.md'), `# Connecticut data status

Generated by \`node scripts/ct/status.mjs\`. ${covered} governments loaded: all 169 towns (some are consolidated cities or a borough) plus the City of Groton. Connecticut has no county governments, so files are grouped by the nine planning regions the Census uses as county equivalents.

| Planning region | Loaded | Fiscal year(s) | Debt |
|---|---|---|---|
${rows.join('\n')}

## Sources
- **Revenue, spending totals, debt:** CT Office of Policy and Management, Municipal Fiscal Indicators: [financial statement information, FY 2020-2023](https://data.ct.gov/d/d6pe-dw46) on data.ct.gov. General-fund actual results for fiscal years ending June 30, not budgets.
- **Spending by department:** Municipal Fiscal Indicators: [Uniform Chart of Accounts, FY 2020-2023](https://data.ct.gov/d/e2qt-k238). Used for a year only when its total matches the financial statements to the dollar.
- **History:** Municipal Fiscal Indicators: [individual town data, 2014-2023](https://data.ct.gov/d/ej6f-y2wf).
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer.

## How Connecticut differs
- **Towns run the schools.** The board of education and any regional school district are paid from the town budget, so school spending (usually more than half the total) is on each report. It is left out of the services and overhead shares so towns compare with other states, where school districts are separate governments.
- **General government is large.** With schools set aside, the median town spends ${median}% of the rest on general government (NJ, NY and PA are 15-17%). Many towns rely on state police and volunteer fire companies or separate fire districts, so their own direct services are small next to the fixed costs of running a town government, such as the clerk, assessor and tax collector. This lowers Connecticut's services and overhead scores. Debt service also includes school construction bonds.
- **Revenue detail is limited.** The state reports revenue only as property tax, state, federal and all other.

## Known gaps
- **Political money is not scored for Connecticut.** Candidates for town office file campaign reports with their town clerk. The State Elections Enforcement Commission's data covers state candidates and only a handful of mayoral campaigns.
- **Transparency practices** have not been checked yet, so they are not scored.
- **Spending not broken down by department** (services and overhead not scored): ${notItemized.length ? notItemized.join(', ') : 'none'}. The state either has no department breakdown for these towns or its total does not match the financial statements.
- **Older year used** because FY 2023's department breakdown is missing or does not match: ${older.length ? older.join(', ') : 'none'}.
- Transfers between a town's own funds and other financing sources (such as bond proceeds) are left out. Enterprise funds (often water and sewer), fire districts, and boroughs and special districts inside towns are separate and not included, except the City of Groton.
`);
console.log(`docs/CT_DATA_STATUS.md: ${covered} governments`);
