#!/usr/bin/env node
// Writes docs/MA_DATA_STATUS.md from the county files in data/real/.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCSV, slugify } from '../lib.mjs';
import { totals } from '../../js/engine/scoring.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const pop = parseCSV(readFileSync(join(ROOT, 'data', 'raw', 'ma', 'popest.csv'), 'latin1'));
const counties = pop.filter((r) => r.sumlev === '050').map((r) => r.name.replace(/ County$/, '')).sort();
const rows = [];
const years = new Map();
const admin = [];
const schools = [];
let covered = 0;
let withFilers = 0;
let withMoney = 0;
let polTotal = 0;
let since = '';
for (const county of counties) {
  const file = join(ROOT, 'data', 'real', `ma-${slugify(county)}.json`);
  if (!existsSync(file)) { rows.push(`| ${county} | not started | | | |`); continue; }
  const { towns } = JSON.parse(readFileSync(file, 'utf8'));
  const n = (f) => towns.filter(f).length;
  const cities = n((t) => t.type === 'City');
  const types = [[towns.length - cities, 'town'], [cities, 'city']].filter(([c]) => c)
    .map(([c, k]) => (k === 'city' ? `${c} ${c === 1 ? 'city' : 'cities'}` : `${c} town${c === 1 ? '' : 's'}`)).join(', ');
  for (const t of towns) {
    (years.get(t.fiscalYear) || years.set(t.fiscalYear, []).get(t.fiscalYear)).push(t.name);
    const tt = totals(t);
    admin.push(tt.adminShare);
    const all = Object.values(t.spending).reduce((a, b) => a + b, 0);
    schools.push((t.spending.education || 0) / all);
    if (t.influence) withFilers++;
    const v = Object.values(t.influence || {}).reduce((a, b) => a + b, 0);
    if (v > 0) withMoney++;
    polTotal += v;
    since ||= (t.sources.find((x) => /Campaign and Political Finance/.test(x.label))?.label.match(/since (\d{4})/) || [])[1] || '';
  }
  covered += towns.length;
  const fy = [...new Set(towns.map((t) => t.fiscalYear))].sort();
  rows.push(`| ${county} | ${towns.length} (${types}) | ${fy.join(', ')} | ${n((t) => typeof t.debt === 'number')} | ${n((t) => t.influence)} |`);
}
const median = (a) => a.sort((x, y) => x - y)[a.length >> 1];
const main = [...years.entries()].sort((a, b) => b[1].length - a[1].length)[0][0];
const other = [...years.entries()].filter(([y]) => y !== main).sort(([a], [b]) => a - b)
  .map(([y, names]) => `FY ${y}: ${names.sort().join(', ')}`);
writeFileSync(join(ROOT, 'docs', 'MA_DATA_STATUS.md'), `# Massachusetts data status

Generated by \`node scripts/ma/status.mjs\`. ${covered} of 351 cities and towns loaded, grouped by the state's 14 counties (most county governments were abolished, but the Census still uses them).

| County | Loaded | Fiscal year(s) | Debt | Political money |
|---|---|---|---|---|
${rows.join('\n')}

## Sources
- **Revenue and spending:** MA Department of Revenue, Division of Local Services (DLS): [Schedule A general fund revenue and expenditures](https://dls-gw.dor.state.ma.us/reports/rdPage.aspx?rdReport=ScheduleA.GenFund_MAIN), FY 2014 on. Actual general-fund results for fiscal years ending June 30, not budgets, with spending by function.
- **Property tax vs. other local taxes:** DLS [local receipts](https://dls-gw.dor.state.ma.us/reports/rdPage.aspx?rdReport=TaxRateRecap.PAGE3.LocalReceiptsAct_vs_Est) (actual motor vehicle, meals, room and other excise collections).
- **Debt:** DLS [long-term debt](https://dls-gw.dor.state.ma.us/reports/rdPage.aspx?rdReport=Dashboard.Cat_6_Reports.LongTermDebt351) (Schedule A Part 10, total outstanding).
- **Political money:** [Office of Campaign and Political Finance](https://www.ocpf.us/) (OCPF) receipts of party ward, town and city committees and of candidates for mayor and city council.
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer.

## How Massachusetts differs
- **Cities and towns run the schools.** Schools and assessments to regional school districts are paid from the general fund, so school spending (a median ${Math.round(median(schools) * 100)}% of the total) is on each report. It is left out of the services and overhead shares so towns compare with states where school districts are separate governments.
- **Fixed costs are spread.** Health insurance, pensions and other benefits for town and school staff are reported together as "fixed costs" and spread across departments by size, schools included. Intergovernmental assessments (charter school tuition, regional transit, county and state charges) and other spending are spread the same way. The median town spends ${Math.round(median(admin) * 100)}% of its non-school budget on general government (NJ, NY and PA are 15-17%).
- **Taxes include excises.** Schedule A "Taxes" include motor vehicle and local option excises (meals, rooms, cannabis). Those are taken from the state's actual local receipts and shown as other local taxes; the rest is property tax.

## Known gaps
- **Political money covers party committees and city candidates.** Party ward, town and city committees and candidates for mayor and city council file with OCPF. Candidates for other town offices (select board, town meeting, school committee in towns) file with their town clerk and are not included. Counted since ${since}: contributions from unions and registered PACs. Corporate contributions are banned in Massachusetts. ${withFilers} of ${covered} towns have at least one filer with OCPF and are scored; ${withMoney} had union or PAC money, $${Math.round(polTotal).toLocaleString('en-US')} in all. Party committees also support state candidates.
- **Transparency practices** have not been checked yet, so they are not scored.
- **Fiscal year.** Most towns use FY ${main}. ${other.length ? `Others: ${other.join('; ')}. A town uses its latest year with actual excise collections on file; late filers use an older year.` : ''}
- Transfers between a town's own funds and other financing sources (such as bond proceeds) are left out. Enterprise funds (often water and sewer) and fire, water and other districts are separate and not included. Debt is all long-term debt the town reports, including enterprise fund borrowing.
`);
console.log(`docs/MA_DATA_STATUS.md: ${covered} cities and towns`);
