#!/usr/bin/env node
// Writes docs/PA_DATA_STATUS.md from the county files in data/real/.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { slugify } from '../lib.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const afr = JSON.parse(readFileSync(join(ROOT, 'data', 'raw', 'pa', 'afr.json'), 'utf8'));
const counties = [...new Set(Object.values(afr).map((g) => g.county))].sort();
const title = (s) => s.toLowerCase().replace(/(^|\s)([a-z])/g, (m, a, b) => a + b.toUpperCase());
const rows = [];
const old = [];
let covered = 0;
for (const county of counties) {
  const file = join(ROOT, 'data', 'real', `pa-${slugify(county)}.json`);
  const inAfr = Object.values(afr).filter((g) => g.county === county).length;
  if (!existsSync(file)) { rows.push(`| ${title(county)} | not started | | |`); continue; }
  const { towns } = JSON.parse(readFileSync(file, 'utf8'));
  const n = (f) => towns.filter(f).length;
  const types = ['Township', 'Borough', 'City', 'Town'].map((k) => [k, n((t) => t.type === k)]).filter(([, c]) => c).map(([k, c]) => `${c} ${k.toLowerCase()}${c === 1 ? '' : k === 'City' ? '' : 's'}`.replace(/citys?$/, c === 1 ? 'city' : 'cities')).join(', ');
  const years = [...new Set(towns.map((t) => t.fiscalYear))].sort();
  old.push(...towns.filter((t) => t.fiscalYear < 2023).map((t) => `${t.name} (${t.fiscalYear})`));
  covered += towns.length;
  rows.push(`| ${title(county)} | ${towns.length} of ${inAfr} (${types}) | ${years.length > 2 ? `${years[0]}-${years.at(-1)}` : years.join(', ')} | ${n((t) => typeof t.debt === 'number')} |`);
}
writeFileSync(join(ROOT, 'docs', 'PA_DATA_STATUS.md'), `# Pennsylvania data status

Generated by \`node scripts/pa/status.mjs\`. ${covered} of ${Object.keys(afr).length} municipalities loaded.

| County | Loaded | Report year(s) | Debt |
|---|---|---|---|
${rows.join('\n')}

## Sources
- **Revenue, spending, debt:** PA Department of Community and Economic Development, [Statewide Municipal Annual Financial Reports](https://apps.dced.pa.gov/munstats-public/ReportInformation2.aspx?report=StatewideMuniAfr) (DCED-CLGS-30), each municipality's latest filed year (mostly 2024; 2025 reports are not published yet). Actual results, not budgets. Line items are checked against each report's total revenues and expenditures during the build.
- **Population:** U.S. Census Bureau 2025 population estimates. **Map location:** Census 2024 Gazetteer.

## Known gaps
- **Political money is not scored for Pennsylvania.** Municipal candidates file campaign reports with their county board of elections; the Department of State's statewide data covers only state-level filers.
- **Transparency practices** have not been checked yet, so they are not scored.
- **Left out:** municipalities with no annual report since 2016, and two (Wheatland Borough, Upper Mahantango Township) that are not in the Census 2025 estimates.
- **Older reports:** ${old.length ? old.join(', ') : 'none'}.
- "Other financing sources and uses" (transfers between funds, borrowing, refinancing) are left out because the statewide report does not break them down. Independent municipal authorities (often water and sewer) file separately and are not included.
- The statewide report does not separate outside legal and engineering costs from general government, so "consultants" is not broken out.
`);
console.log(`docs/PA_DATA_STATUS.md: ${covered} municipalities`);
